class_name LanRoundEvent
extends RefCounted

enum Kind {
	HOLDER_CHANGED = 1,
	SCORE_CHANGED = 2,
	ROUND_COMPLETED = 3,
	HAZARD_STATE = 4,
	DAMAGE_CONFIRMED = 5,
	WEAPON_STATE = 6,
	HIT_CONFIRMED = 7,
}

enum Subject {
	CROWN = 1,
	BOMB = 2,
	FOOTBALL = 3,
	BATEBALL = 4,
	TORNADO = 5,
	SHOOTER = 6,
	ELIMINATION_BALL = 7,
}

enum Action {
	FOOTBALL_KICK = 1,
	BATEBALL_SWING = 2,
	CHARACTER_PUSH = 3,
	BATEBALL_IMPACT = 4,
	SHOOTER_SHOT = 5,
	SHOOTER_RELOAD = 6,
	ELIMINATION_BALL_THROW = 7,
}
